baseURL = "https://www.gottalottasoul.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Blake's R Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-4974577-3"

[params]
title = "Blake's R Blog"
author = "Blake Abbenante"
description = "My not-so-polished blog about R"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
displayMode = "dark"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/blakeabbenante/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/gottalottasoul"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/abbenante"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:mail@gottalottasoul.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
